version: "3"

services:

  db_engine:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: northwind_demo
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    networks:
      - db_network

  db_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dbadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: dbpassword
    ports:
      - "8080:80"
    networks:
      - db_network
    depends_on:
      - db_engine

networks:
  db_network:
    driver: bridge
